
x11()
par(mfrow=c(2,2))
setwd("~/RPAI/online/online-2pulse-3param-v6")
source("test_engine.R")
setwd("~/RPAI/online/online-3pulse-3param-v7")
source("test_engine_multi.R")
setwd("~/RPAI/online/online-4pulse-3param-v2")
source("test_engine_multi.R")
setwd("~/RPAI/online/online-5pulse-3param-v2")
source("test_engine_multi.R")